// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newAdminDataScope(db *gorm.DB, opts ...gen.DOOption) adminDataScope {
	_adminDataScope := adminDataScope{}

	_adminDataScope.adminDataScopeDo.UseDB(db, opts...)
	_adminDataScope.adminDataScopeDo.UseModel(&model.AdminDataScope{})

	tableName := _adminDataScope.adminDataScopeDo.TableName()
	_adminDataScope.ALL = field.NewAsterisk(tableName)
	_adminDataScope.UserID = field.NewUint64(tableName, "user_id")
	_adminDataScope.DataDomainID = field.NewUint64(tableName, "data_domain_id")
	_adminDataScope.CreatedAt = field.NewTime(tableName, "created_at")

	_adminDataScope.fillFieldMap()

	return _adminDataScope
}

// adminDataScope administrator alumni data scopes
type adminDataScope struct {
	adminDataScopeDo adminDataScopeDo

	ALL          field.Asterisk
	UserID       field.Uint64 // administrator user id
	DataDomainID field.Uint64 // allowed alumni data domain id
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (a adminDataScope) Table(newTableName string) *adminDataScope {
	a.adminDataScopeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminDataScope) As(alias string) *adminDataScope {
	a.adminDataScopeDo.DO = *(a.adminDataScopeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminDataScope) updateTableName(table string) *adminDataScope {
	a.ALL = field.NewAsterisk(table)
	a.UserID = field.NewUint64(table, "user_id")
	a.DataDomainID = field.NewUint64(table, "data_domain_id")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *adminDataScope) WithContext(ctx context.Context) *adminDataScopeDo {
	return a.adminDataScopeDo.WithContext(ctx)
}

func (a adminDataScope) TableName() string { return a.adminDataScopeDo.TableName() }

func (a adminDataScope) Alias() string { return a.adminDataScopeDo.Alias() }

func (a adminDataScope) Columns(cols ...field.Expr) gen.Columns {
	return a.adminDataScopeDo.Columns(cols...)
}

func (a *adminDataScope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminDataScope) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["data_domain_id"] = a.DataDomainID
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a adminDataScope) clone(db *gorm.DB) adminDataScope {
	a.adminDataScopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminDataScope) replaceDB(db *gorm.DB) adminDataScope {
	a.adminDataScopeDo.ReplaceDB(db)
	return a
}

type adminDataScopeDo struct{ gen.DO }

func (a adminDataScopeDo) Debug() *adminDataScopeDo {
	return a.withDO(a.DO.Debug())
}

func (a adminDataScopeDo) WithContext(ctx context.Context) *adminDataScopeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminDataScopeDo) ReadDB() *adminDataScopeDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminDataScopeDo) WriteDB() *adminDataScopeDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminDataScopeDo) Session(config *gorm.Session) *adminDataScopeDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminDataScopeDo) Clauses(conds ...clause.Expression) *adminDataScopeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminDataScopeDo) Returning(value interface{}, columns ...string) *adminDataScopeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminDataScopeDo) Not(conds ...gen.Condition) *adminDataScopeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminDataScopeDo) Or(conds ...gen.Condition) *adminDataScopeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminDataScopeDo) Select(conds ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminDataScopeDo) Where(conds ...gen.Condition) *adminDataScopeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminDataScopeDo) Order(conds ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminDataScopeDo) Distinct(cols ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminDataScopeDo) Omit(cols ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminDataScopeDo) Join(table schema.Tabler, on ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminDataScopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminDataScopeDo) RightJoin(table schema.Tabler, on ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminDataScopeDo) Group(cols ...field.Expr) *adminDataScopeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminDataScopeDo) Having(conds ...gen.Condition) *adminDataScopeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminDataScopeDo) Limit(limit int) *adminDataScopeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminDataScopeDo) Offset(offset int) *adminDataScopeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminDataScopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *adminDataScopeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminDataScopeDo) Unscoped() *adminDataScopeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminDataScopeDo) Create(values ...*model.AdminDataScope) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminDataScopeDo) CreateInBatches(values []*model.AdminDataScope, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminDataScopeDo) Save(values ...*model.AdminDataScope) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminDataScopeDo) First() (*model.AdminDataScope, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminDataScope), nil
	}
}

func (a adminDataScopeDo) Take() (*model.AdminDataScope, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminDataScope), nil
	}
}

func (a adminDataScopeDo) Last() (*model.AdminDataScope, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminDataScope), nil
	}
}

func (a adminDataScopeDo) Find() ([]*model.AdminDataScope, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminDataScope), err
}

func (a adminDataScopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminDataScope, err error) {
	buf := make([]*model.AdminDataScope, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminDataScopeDo) FindInBatches(result *[]*model.AdminDataScope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminDataScopeDo) Attrs(attrs ...field.AssignExpr) *adminDataScopeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminDataScopeDo) Assign(attrs ...field.AssignExpr) *adminDataScopeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminDataScopeDo) Joins(fields ...field.RelationField) *adminDataScopeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminDataScopeDo) Preload(fields ...field.RelationField) *adminDataScopeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminDataScopeDo) FirstOrInit() (*model.AdminDataScope, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminDataScope), nil
	}
}

func (a adminDataScopeDo) FirstOrCreate() (*model.AdminDataScope, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminDataScope), nil
	}
}

func (a adminDataScopeDo) FindByPage(offset int, limit int) (result []*model.AdminDataScope, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminDataScopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminDataScopeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminDataScopeDo) Delete(models ...*model.AdminDataScope) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminDataScopeDo) withDO(do gen.Dao) *adminDataScopeDo {
	a.DO = *do.(*gen.DO)
	return a
}
