// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newAlumniFile(db *gorm.DB, opts ...gen.DOOption) alumniFile {
	_alumniFile := alumniFile{}

	_alumniFile.alumniFileDo.UseDB(db, opts...)
	_alumniFile.alumniFileDo.UseModel(&model.AlumniFile{})

	tableName := _alumniFile.alumniFileDo.TableName()
	_alumniFile.ALL = field.NewAsterisk(tableName)
	_alumniFile.ID = field.NewUint64(tableName, "id")
	_alumniFile.AlumniID = field.NewUint64(tableName, "alumni_id")
	_alumniFile.FileType = field.NewString(tableName, "file_type")
	_alumniFile.ObjectKey = field.NewString(tableName, "object_key")
	_alumniFile.OriginalName = field.NewString(tableName, "original_name")
	_alumniFile.FileSize = field.NewUint64(tableName, "file_size")
	_alumniFile.MimeType = field.NewString(tableName, "mime_type")
	_alumniFile.UploadedBy = field.NewUint64(tableName, "uploaded_by")
	_alumniFile.Status = field.NewString(tableName, "status")
	_alumniFile.CreatedAt = field.NewTime(tableName, "created_at")
	_alumniFile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_alumniFile.DeletedAt = field.NewField(tableName, "deleted_at")

	_alumniFile.fillFieldMap()

	return _alumniFile
}

// alumniFile 校友档案文件
type alumniFile struct {
	alumniFileDo alumniFileDo

	ALL          field.Asterisk
	ID           field.Uint64
	AlumniID     field.Uint64 // 校友档案 ID
	FileType     field.String // degree_archive / academic_record
	ObjectKey    field.String // MinIO 对象路径
	OriginalName field.String // 原始文件名
	FileSize     field.Uint64 // 文件大小（字节）
	MimeType     field.String // MIME 类型
	UploadedBy   field.Uint64 // 上传者用户 ID
	Status       field.String // active / deleted
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (a alumniFile) Table(newTableName string) *alumniFile {
	a.alumniFileDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alumniFile) As(alias string) *alumniFile {
	a.alumniFileDo.DO = *(a.alumniFileDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alumniFile) updateTableName(table string) *alumniFile {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.AlumniID = field.NewUint64(table, "alumni_id")
	a.FileType = field.NewString(table, "file_type")
	a.ObjectKey = field.NewString(table, "object_key")
	a.OriginalName = field.NewString(table, "original_name")
	a.FileSize = field.NewUint64(table, "file_size")
	a.MimeType = field.NewString(table, "mime_type")
	a.UploadedBy = field.NewUint64(table, "uploaded_by")
	a.Status = field.NewString(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *alumniFile) WithContext(ctx context.Context) *alumniFileDo {
	return a.alumniFileDo.WithContext(ctx)
}

func (a alumniFile) TableName() string { return a.alumniFileDo.TableName() }

func (a alumniFile) Alias() string { return a.alumniFileDo.Alias() }

func (a alumniFile) Columns(cols ...field.Expr) gen.Columns { return a.alumniFileDo.Columns(cols...) }

func (a *alumniFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alumniFile) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["alumni_id"] = a.AlumniID
	a.fieldMap["file_type"] = a.FileType
	a.fieldMap["object_key"] = a.ObjectKey
	a.fieldMap["original_name"] = a.OriginalName
	a.fieldMap["file_size"] = a.FileSize
	a.fieldMap["mime_type"] = a.MimeType
	a.fieldMap["uploaded_by"] = a.UploadedBy
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a alumniFile) clone(db *gorm.DB) alumniFile {
	a.alumniFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alumniFile) replaceDB(db *gorm.DB) alumniFile {
	a.alumniFileDo.ReplaceDB(db)
	return a
}

type alumniFileDo struct{ gen.DO }

func (a alumniFileDo) Debug() *alumniFileDo {
	return a.withDO(a.DO.Debug())
}

func (a alumniFileDo) WithContext(ctx context.Context) *alumniFileDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alumniFileDo) ReadDB() *alumniFileDo {
	return a.Clauses(dbresolver.Read)
}

func (a alumniFileDo) WriteDB() *alumniFileDo {
	return a.Clauses(dbresolver.Write)
}

func (a alumniFileDo) Session(config *gorm.Session) *alumniFileDo {
	return a.withDO(a.DO.Session(config))
}

func (a alumniFileDo) Clauses(conds ...clause.Expression) *alumniFileDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alumniFileDo) Returning(value interface{}, columns ...string) *alumniFileDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alumniFileDo) Not(conds ...gen.Condition) *alumniFileDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alumniFileDo) Or(conds ...gen.Condition) *alumniFileDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alumniFileDo) Select(conds ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alumniFileDo) Where(conds ...gen.Condition) *alumniFileDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alumniFileDo) Order(conds ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alumniFileDo) Distinct(cols ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alumniFileDo) Omit(cols ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alumniFileDo) Join(table schema.Tabler, on ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alumniFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alumniFileDo) RightJoin(table schema.Tabler, on ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alumniFileDo) Group(cols ...field.Expr) *alumniFileDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alumniFileDo) Having(conds ...gen.Condition) *alumniFileDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alumniFileDo) Limit(limit int) *alumniFileDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alumniFileDo) Offset(offset int) *alumniFileDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alumniFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *alumniFileDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alumniFileDo) Unscoped() *alumniFileDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alumniFileDo) Create(values ...*model.AlumniFile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alumniFileDo) CreateInBatches(values []*model.AlumniFile, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alumniFileDo) Save(values ...*model.AlumniFile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alumniFileDo) First() (*model.AlumniFile, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniFile), nil
	}
}

func (a alumniFileDo) Take() (*model.AlumniFile, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniFile), nil
	}
}

func (a alumniFileDo) Last() (*model.AlumniFile, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniFile), nil
	}
}

func (a alumniFileDo) Find() ([]*model.AlumniFile, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlumniFile), err
}

func (a alumniFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlumniFile, err error) {
	buf := make([]*model.AlumniFile, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alumniFileDo) FindInBatches(result *[]*model.AlumniFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alumniFileDo) Attrs(attrs ...field.AssignExpr) *alumniFileDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alumniFileDo) Assign(attrs ...field.AssignExpr) *alumniFileDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alumniFileDo) Joins(fields ...field.RelationField) *alumniFileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alumniFileDo) Preload(fields ...field.RelationField) *alumniFileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alumniFileDo) FirstOrInit() (*model.AlumniFile, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniFile), nil
	}
}

func (a alumniFileDo) FirstOrCreate() (*model.AlumniFile, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniFile), nil
	}
}

func (a alumniFileDo) FindByPage(offset int, limit int) (result []*model.AlumniFile, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alumniFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alumniFileDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alumniFileDo) Delete(models ...*model.AlumniFile) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alumniFileDo) withDO(do gen.Dao) *alumniFileDo {
	a.DO = *do.(*gen.DO)
	return a
}
