// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newAlumniProfile(db *gorm.DB, opts ...gen.DOOption) alumniProfile {
	_alumniProfile := alumniProfile{}

	_alumniProfile.alumniProfileDo.UseDB(db, opts...)
	_alumniProfile.alumniProfileDo.UseModel(&model.AlumniProfile{})

	tableName := _alumniProfile.alumniProfileDo.TableName()
	_alumniProfile.ALL = field.NewAsterisk(tableName)
	_alumniProfile.ID = field.NewUint64(tableName, "id")
	_alumniProfile.Name = field.NewString(tableName, "name")
	_alumniProfile.Grade = field.NewString(tableName, "grade")
	_alumniProfile.ClassName = field.NewString(tableName, "class_name")
	_alumniProfile.Cohort = field.NewString(tableName, "cohort")
	_alumniProfile.Counselor = field.NewString(tableName, "counselor")
	_alumniProfile.Mentor = field.NewString(tableName, "mentor")
	_alumniProfile.Major = field.NewString(tableName, "major")
	_alumniProfile.TrainingMode = field.NewString(tableName, "training_mode")
	_alumniProfile.Industry = field.NewString(tableName, "industry")
	_alumniProfile.WorkUnit = field.NewString(tableName, "work_unit")
	_alumniProfile.Position = field.NewString(tableName, "position")
	_alumniProfile.MailingAddress = field.NewString(tableName, "mailing_address")
	_alumniProfile.Gender = field.NewString(tableName, "gender")
	_alumniProfile.Mobile = field.NewString(tableName, "mobile")
	_alumniProfile.Remark = field.NewString(tableName, "remark")
	_alumniProfile.Status = field.NewString(tableName, "status")
	_alumniProfile.CreatedBy = field.NewUint64(tableName, "created_by")
	_alumniProfile.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_alumniProfile.CreatedAt = field.NewTime(tableName, "created_at")
	_alumniProfile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_alumniProfile.DeletedAt = field.NewField(tableName, "deleted_at")

	_alumniProfile.fillFieldMap()

	return _alumniProfile
}

// alumniProfile alumni profiles
type alumniProfile struct {
	alumniProfileDo alumniProfileDo

	ALL            field.Asterisk
	ID             field.Uint64
	Name           field.String // name
	Grade          field.String // grade
	ClassName      field.String // class
	Cohort         field.String // cohort
	Counselor      field.String // counselor
	Mentor         field.String // mentor
	Major          field.String // major
	TrainingMode   field.String // training mode
	Industry       field.String // industry
	WorkUnit       field.String // work unit
	Position       field.String // position
	MailingAddress field.String // mailing address
	Gender         field.String // gender
	Mobile         field.String // mobile
	Remark         field.String // admin remark
	Status         field.String // active/deleted
	CreatedBy      field.Uint64 // creator user id
	UpdatedBy      field.Uint64 // updater user id
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (a alumniProfile) Table(newTableName string) *alumniProfile {
	a.alumniProfileDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alumniProfile) As(alias string) *alumniProfile {
	a.alumniProfileDo.DO = *(a.alumniProfileDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alumniProfile) updateTableName(table string) *alumniProfile {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Grade = field.NewString(table, "grade")
	a.ClassName = field.NewString(table, "class_name")
	a.Cohort = field.NewString(table, "cohort")
	a.Counselor = field.NewString(table, "counselor")
	a.Mentor = field.NewString(table, "mentor")
	a.Major = field.NewString(table, "major")
	a.TrainingMode = field.NewString(table, "training_mode")
	a.Industry = field.NewString(table, "industry")
	a.WorkUnit = field.NewString(table, "work_unit")
	a.Position = field.NewString(table, "position")
	a.MailingAddress = field.NewString(table, "mailing_address")
	a.Gender = field.NewString(table, "gender")
	a.Mobile = field.NewString(table, "mobile")
	a.Remark = field.NewString(table, "remark")
	a.Status = field.NewString(table, "status")
	a.CreatedBy = field.NewUint64(table, "created_by")
	a.UpdatedBy = field.NewUint64(table, "updated_by")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *alumniProfile) WithContext(ctx context.Context) *alumniProfileDo {
	return a.alumniProfileDo.WithContext(ctx)
}

func (a alumniProfile) TableName() string { return a.alumniProfileDo.TableName() }

func (a alumniProfile) Alias() string { return a.alumniProfileDo.Alias() }

func (a alumniProfile) Columns(cols ...field.Expr) gen.Columns {
	return a.alumniProfileDo.Columns(cols...)
}

func (a *alumniProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alumniProfile) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 22)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["grade"] = a.Grade
	a.fieldMap["class_name"] = a.ClassName
	a.fieldMap["cohort"] = a.Cohort
	a.fieldMap["counselor"] = a.Counselor
	a.fieldMap["mentor"] = a.Mentor
	a.fieldMap["major"] = a.Major
	a.fieldMap["training_mode"] = a.TrainingMode
	a.fieldMap["industry"] = a.Industry
	a.fieldMap["work_unit"] = a.WorkUnit
	a.fieldMap["position"] = a.Position
	a.fieldMap["mailing_address"] = a.MailingAddress
	a.fieldMap["gender"] = a.Gender
	a.fieldMap["mobile"] = a.Mobile
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_by"] = a.CreatedBy
	a.fieldMap["updated_by"] = a.UpdatedBy
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a alumniProfile) clone(db *gorm.DB) alumniProfile {
	a.alumniProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alumniProfile) replaceDB(db *gorm.DB) alumniProfile {
	a.alumniProfileDo.ReplaceDB(db)
	return a
}

type alumniProfileDo struct{ gen.DO }

func (a alumniProfileDo) Debug() *alumniProfileDo {
	return a.withDO(a.DO.Debug())
}

func (a alumniProfileDo) WithContext(ctx context.Context) *alumniProfileDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alumniProfileDo) ReadDB() *alumniProfileDo {
	return a.Clauses(dbresolver.Read)
}

func (a alumniProfileDo) WriteDB() *alumniProfileDo {
	return a.Clauses(dbresolver.Write)
}

func (a alumniProfileDo) Session(config *gorm.Session) *alumniProfileDo {
	return a.withDO(a.DO.Session(config))
}

func (a alumniProfileDo) Clauses(conds ...clause.Expression) *alumniProfileDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alumniProfileDo) Returning(value interface{}, columns ...string) *alumniProfileDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alumniProfileDo) Not(conds ...gen.Condition) *alumniProfileDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alumniProfileDo) Or(conds ...gen.Condition) *alumniProfileDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alumniProfileDo) Select(conds ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alumniProfileDo) Where(conds ...gen.Condition) *alumniProfileDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alumniProfileDo) Order(conds ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alumniProfileDo) Distinct(cols ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alumniProfileDo) Omit(cols ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alumniProfileDo) Join(table schema.Tabler, on ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alumniProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alumniProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alumniProfileDo) Group(cols ...field.Expr) *alumniProfileDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alumniProfileDo) Having(conds ...gen.Condition) *alumniProfileDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alumniProfileDo) Limit(limit int) *alumniProfileDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alumniProfileDo) Offset(offset int) *alumniProfileDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alumniProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *alumniProfileDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alumniProfileDo) Unscoped() *alumniProfileDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alumniProfileDo) Create(values ...*model.AlumniProfile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alumniProfileDo) CreateInBatches(values []*model.AlumniProfile, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alumniProfileDo) Save(values ...*model.AlumniProfile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alumniProfileDo) First() (*model.AlumniProfile, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniProfile), nil
	}
}

func (a alumniProfileDo) Take() (*model.AlumniProfile, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniProfile), nil
	}
}

func (a alumniProfileDo) Last() (*model.AlumniProfile, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniProfile), nil
	}
}

func (a alumniProfileDo) Find() ([]*model.AlumniProfile, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlumniProfile), err
}

func (a alumniProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlumniProfile, err error) {
	buf := make([]*model.AlumniProfile, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alumniProfileDo) FindInBatches(result *[]*model.AlumniProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alumniProfileDo) Attrs(attrs ...field.AssignExpr) *alumniProfileDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alumniProfileDo) Assign(attrs ...field.AssignExpr) *alumniProfileDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alumniProfileDo) Joins(fields ...field.RelationField) *alumniProfileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alumniProfileDo) Preload(fields ...field.RelationField) *alumniProfileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alumniProfileDo) FirstOrInit() (*model.AlumniProfile, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniProfile), nil
	}
}

func (a alumniProfileDo) FirstOrCreate() (*model.AlumniProfile, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlumniProfile), nil
	}
}

func (a alumniProfileDo) FindByPage(offset int, limit int) (result []*model.AlumniProfile, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alumniProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alumniProfileDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alumniProfileDo) Delete(models ...*model.AlumniProfile) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alumniProfileDo) withDO(do gen.Dao) *alumniProfileDo {
	a.DO = *do.(*gen.DO)
	return a
}
