// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newDataDomain(db *gorm.DB, opts ...gen.DOOption) dataDomain {
	_dataDomain := dataDomain{}

	_dataDomain.dataDomainDo.UseDB(db, opts...)
	_dataDomain.dataDomainDo.UseModel(&model.DataDomain{})

	tableName := _dataDomain.dataDomainDo.TableName()
	_dataDomain.ALL = field.NewAsterisk(tableName)
	_dataDomain.ID = field.NewUint64(tableName, "id")
	_dataDomain.Code = field.NewString(tableName, "code")
	_dataDomain.Name = field.NewString(tableName, "name")
	_dataDomain.Status = field.NewString(tableName, "status")
	_dataDomain.SortOrder = field.NewInt32(tableName, "sort_order")
	_dataDomain.CreatedAt = field.NewTime(tableName, "created_at")
	_dataDomain.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dataDomain.fillFieldMap()

	return _dataDomain
}

// dataDomain alumni data domains
type dataDomain struct {
	dataDomainDo dataDomainDo

	ALL       field.Asterisk
	ID        field.Uint64
	Code      field.String // stable domain code
	Name      field.String // display name
	Status    field.String // active/disabled
	SortOrder field.Int32  // display order
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (d dataDomain) Table(newTableName string) *dataDomain {
	d.dataDomainDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataDomain) As(alias string) *dataDomain {
	d.dataDomainDo.DO = *(d.dataDomainDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataDomain) updateTableName(table string) *dataDomain {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint64(table, "id")
	d.Code = field.NewString(table, "code")
	d.Name = field.NewString(table, "name")
	d.Status = field.NewString(table, "status")
	d.SortOrder = field.NewInt32(table, "sort_order")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dataDomain) WithContext(ctx context.Context) *dataDomainDo {
	return d.dataDomainDo.WithContext(ctx)
}

func (d dataDomain) TableName() string { return d.dataDomainDo.TableName() }

func (d dataDomain) Alias() string { return d.dataDomainDo.Alias() }

func (d dataDomain) Columns(cols ...field.Expr) gen.Columns { return d.dataDomainDo.Columns(cols...) }

func (d *dataDomain) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataDomain) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["code"] = d.Code
	d.fieldMap["name"] = d.Name
	d.fieldMap["status"] = d.Status
	d.fieldMap["sort_order"] = d.SortOrder
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dataDomain) clone(db *gorm.DB) dataDomain {
	d.dataDomainDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataDomain) replaceDB(db *gorm.DB) dataDomain {
	d.dataDomainDo.ReplaceDB(db)
	return d
}

type dataDomainDo struct{ gen.DO }

func (d dataDomainDo) Debug() *dataDomainDo {
	return d.withDO(d.DO.Debug())
}

func (d dataDomainDo) WithContext(ctx context.Context) *dataDomainDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataDomainDo) ReadDB() *dataDomainDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataDomainDo) WriteDB() *dataDomainDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataDomainDo) Session(config *gorm.Session) *dataDomainDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataDomainDo) Clauses(conds ...clause.Expression) *dataDomainDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataDomainDo) Returning(value interface{}, columns ...string) *dataDomainDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataDomainDo) Not(conds ...gen.Condition) *dataDomainDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataDomainDo) Or(conds ...gen.Condition) *dataDomainDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataDomainDo) Select(conds ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataDomainDo) Where(conds ...gen.Condition) *dataDomainDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataDomainDo) Order(conds ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataDomainDo) Distinct(cols ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataDomainDo) Omit(cols ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataDomainDo) Join(table schema.Tabler, on ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataDomainDo) LeftJoin(table schema.Tabler, on ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataDomainDo) RightJoin(table schema.Tabler, on ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataDomainDo) Group(cols ...field.Expr) *dataDomainDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataDomainDo) Having(conds ...gen.Condition) *dataDomainDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataDomainDo) Limit(limit int) *dataDomainDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataDomainDo) Offset(offset int) *dataDomainDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataDomainDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *dataDomainDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataDomainDo) Unscoped() *dataDomainDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataDomainDo) Create(values ...*model.DataDomain) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataDomainDo) CreateInBatches(values []*model.DataDomain, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataDomainDo) Save(values ...*model.DataDomain) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataDomainDo) First() (*model.DataDomain, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDomain), nil
	}
}

func (d dataDomainDo) Take() (*model.DataDomain, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDomain), nil
	}
}

func (d dataDomainDo) Last() (*model.DataDomain, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDomain), nil
	}
}

func (d dataDomainDo) Find() ([]*model.DataDomain, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataDomain), err
}

func (d dataDomainDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDomain, err error) {
	buf := make([]*model.DataDomain, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataDomainDo) FindInBatches(result *[]*model.DataDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataDomainDo) Attrs(attrs ...field.AssignExpr) *dataDomainDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataDomainDo) Assign(attrs ...field.AssignExpr) *dataDomainDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataDomainDo) Joins(fields ...field.RelationField) *dataDomainDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataDomainDo) Preload(fields ...field.RelationField) *dataDomainDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataDomainDo) FirstOrInit() (*model.DataDomain, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDomain), nil
	}
}

func (d dataDomainDo) FirstOrCreate() (*model.DataDomain, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDomain), nil
	}
}

func (d dataDomainDo) FindByPage(offset int, limit int) (result []*model.DataDomain, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataDomainDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataDomainDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataDomainDo) Delete(models ...*model.DataDomain) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataDomainDo) withDO(do gen.Dao) *dataDomainDo {
	d.DO = *do.(*gen.DO)
	return d
}
