// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminDataScope = "admin_data_scopes"

// AdminDataScope administrator alumni data scopes
type AdminDataScope struct {
	UserID       uint64    `gorm:"column:user_id;type:bigint unsigned;primaryKey;comment:administrator user id" json:"user_id"`                                                                         // administrator user id
	DataDomainID uint64    `gorm:"column:data_domain_id;type:bigint unsigned;primaryKey;index:fk_admin_data_scopes_data_domain,priority:1;comment:allowed alumni data domain id" json:"data_domain_id"` // allowed alumni data domain id
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AdminDataScope's table name
func (*AdminDataScope) TableName() string {
	return TableNameAdminDataScope
}
