// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminPermission = "admin_permissions"

// AdminPermission administrator permission codes
type AdminPermission struct {
	UserID         uint64    `gorm:"column:user_id;type:bigint unsigned;primaryKey;comment:administrator user id" json:"user_id"`        // administrator user id
	PermissionCode string    `gorm:"column:permission_code;type:varchar(100);primaryKey;comment:permission code" json:"permission_code"` // permission code
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AdminPermission's table name
func (*AdminPermission) TableName() string {
	return TableNameAdminPermission
}
