// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAlumniFile = "alumni_files"

// AlumniFile 校友档案文件
type AlumniFile struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	AlumniID     uint64         `gorm:"column:alumni_id;type:bigint unsigned;not null;index:idx_af_alumni_id,priority:1;index:idx_af_alumni_type,priority:1;comment:校友档案 ID" json:"alumni_id"`                      // 校友档案 ID
	FileType     string         `gorm:"column:file_type;type:varchar(32);not null;index:idx_af_alumni_type,priority:2;index:idx_af_file_type,priority:1;comment:degree_archive / academic_record" json:"file_type"` // degree_archive / academic_record
	ObjectKey    string         `gorm:"column:object_key;type:varchar(512);not null;comment:MinIO 对象路径" json:"object_key"`                                                                                          // MinIO 对象路径
	OriginalName string         `gorm:"column:original_name;type:varchar(255);not null;comment:原始文件名" json:"original_name"`                                                                                         // 原始文件名
	FileSize     uint64         `gorm:"column:file_size;type:bigint unsigned;not null;comment:文件大小（字节）" json:"file_size"`                                                                                           // 文件大小（字节）
	MimeType     string         `gorm:"column:mime_type;type:varchar(128);not null;comment:MIME 类型" json:"mime_type"`                                                                                               // MIME 类型
	UploadedBy   *uint64        `gorm:"column:uploaded_by;type:bigint unsigned;comment:上传者用户 ID" json:"uploaded_by"`                                                                                                // 上传者用户 ID
	Status       string         `gorm:"column:status;type:varchar(32);not null;index:idx_af_status,priority:1;default:active;comment:active / deleted" json:"status"`                                               // active / deleted
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName AlumniFile's table name
func (*AlumniFile) TableName() string {
	return TableNameAlumniFile
}
