// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAlumniProfile = "alumni_profiles"

// AlumniProfile alumni profiles
type AlumniProfile struct {
	ID             uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name           string         `gorm:"column:name;type:varchar(100);not null;index:ft_alumni_search,priority:1;index:idx_alumni_name,priority:1;comment:name" json:"name"` // name
	Grade          string         `gorm:"column:grade;type:varchar(50);not null;index:idx_alumni_grade,priority:1;comment:grade" json:"grade"`                                // grade
	ClassName      *string        `gorm:"column:class_name;type:varchar(100);index:idx_alumni_class_name,priority:1;comment:class" json:"class_name"`                         // class
	Cohort         *string        `gorm:"column:cohort;type:varchar(50);index:idx_alumni_cohort,priority:1;comment:cohort" json:"cohort"`                                     // cohort
	Counselor      *string        `gorm:"column:counselor;type:varchar(100);index:ft_alumni_search,priority:5;comment:counselor" json:"counselor"`                            // counselor
	Mentor         *string        `gorm:"column:mentor;type:varchar(100);index:ft_alumni_search,priority:4;comment:mentor" json:"mentor"`                                     // mentor
	Major          *string        `gorm:"column:major;type:varchar(100);index:idx_alumni_major,priority:1;comment:major" json:"major"`                                        // major
	TrainingMode   *string        `gorm:"column:training_mode;type:varchar(50);index:idx_alumni_training_mode,priority:1;comment:training mode" json:"training_mode"`         // training mode
	Industry       *string        `gorm:"column:industry;type:varchar(100);index:idx_alumni_industry,priority:1;comment:industry" json:"industry"`                            // industry
	WorkUnit       *string        `gorm:"column:work_unit;type:varchar(255);index:ft_alumni_search,priority:2;comment:work unit" json:"work_unit"`                            // work unit
	Position       *string        `gorm:"column:position;type:varchar(100);index:ft_alumni_search,priority:3;comment:position" json:"position"`                               // position
	MailingAddress *string        `gorm:"column:mailing_address;type:varchar(255);comment:mailing address" json:"mailing_address"`                                            // mailing address
	Gender         *string        `gorm:"column:gender;type:varchar(20);comment:gender" json:"gender"`                                                                        // gender
	Mobile         *string        `gorm:"column:mobile;type:varchar(30);index:idx_alumni_mobile,priority:1;comment:mobile" json:"mobile"`                                     // mobile
	Email          *string        `gorm:"column:email;type:varchar(255);index:idx_alumni_email,priority:1;comment:email address" json:"email"`                                // email address
	Remark         *string        `gorm:"column:remark;type:text;comment:admin remark" json:"remark"`                                                                         // admin remark
	Status         string         `gorm:"column:status;type:varchar(32);not null;index:idx_alumni_status,priority:1;default:active;comment:active/deleted" json:"status"`     // active/deleted
	CreatedBy      *uint64        `gorm:"column:created_by;type:bigint unsigned;comment:creator user id" json:"created_by"`                                                   // creator user id
	UpdatedBy      *uint64        `gorm:"column:updated_by;type:bigint unsigned;comment:updater user id" json:"updated_by"`                                                   // updater user id
	CreatedAt      time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName AlumniProfile's table name
func (*AlumniProfile) TableName() string {
	return TableNameAlumniProfile
}
