// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataDomain = "data_domains"

// DataDomain alumni data domains
type DataDomain struct {
	ID        uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Code      string    `gorm:"column:code;type:varchar(64);not null;uniqueIndex:uk_data_domains_code,priority:1;comment:stable domain code" json:"code"`              // stable domain code
	Name      string    `gorm:"column:name;type:varchar(100);not null;comment:display name" json:"name"`                                                               // display name
	Status    string    `gorm:"column:status;type:varchar(32);not null;index:idx_data_domains_status,priority:1;default:active;comment:active/disabled" json:"status"` // active/disabled
	SortOrder int32     `gorm:"column:sort_order;type:int;not null;comment:display order" json:"sort_order"`                                                           // display order
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName DataDomain's table name
func (*DataDomain) TableName() string {
	return TableNameDataDomain
}
