// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User user accounts
type User struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Account      string         `gorm:"column:account;type:varchar(100);not null;uniqueIndex:account,priority:1;comment:login account" json:"account"`                          // login account
	PasswordHash string         `gorm:"column:password_hash;type:varchar(255);not null;comment:password hash" json:"password_hash"`                                             // password hash
	Role         string         `gorm:"column:role;type:varchar(32);not null;index:idx_users_role,priority:1;comment:alumni/admin/super_admin" json:"role"`                     // alumni/admin/super_admin
	AlumniID     *uint64        `gorm:"column:alumni_id;type:bigint unsigned;index:idx_users_alumni_id,priority:1;comment:linked alumni profile id" json:"alumni_id"`           // linked alumni profile id
	RealName     *string        `gorm:"column:real_name;type:varchar(100);comment:real name" json:"real_name"`                                                                  // real name
	Mobile       *string        `gorm:"column:mobile;type:varchar(30);uniqueIndex:uk_users_mobile,priority:1;comment:mobile or backup contact" json:"mobile"`                   // mobile or backup contact
	Email        *string        `gorm:"column:email;type:varchar(255);uniqueIndex:uk_users_email,priority:1;comment:email address" json:"email"`                                // email address
	Status       string         `gorm:"column:status;type:varchar(32);not null;index:idx_users_status,priority:1;default:active;comment:active/disabled/deleted" json:"status"` // active/disabled/deleted
	LastLoginAt  *time.Time     `gorm:"column:last_login_at;type:datetime;comment:last login time" json:"last_login_at"`                                                        // last login time
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
